# Copyright © 2025, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: velero.io/v1
kind: Backup
metadata:
  name: sas-viya4-backup-TIMESTAMP_PLACEHOLDER
  namespace: velero
spec:
  includedNamespaces:
    - NAMESPACE_PLACEHOLDER
  snapshotVolumes: true
  defaultVolumesToFsBackup: false
  csiSnapshotTimeout: 2h
  includeClusterResources: true
  ttl: 720h0m0s
